/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


/* Header for class epfl_ch_opencvdraft_OpenCvModule */
#ifndef _Included_ch_epfl_droneproject_module_OpenCvModule
#define _Included_ch_epfl_droneproject_module_OpenCvModule
#ifdef __cplusplus
extern "C" {
#endif



/*
 * Class:     ch_epfl_droneproject_module_OpenCvModule
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_droneproject_module_OpenCvModule_nativeCreateObject
        (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ch_epfl_droneproject_module_OpenCvModule
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_droneproject_module_OpenCvModule_nativeDestroyObject
        (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_epfl_droneproject_module_OpenCvModule
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_droneproject_module_OpenCvModule_nativeStart
        (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_epfl_droneproject_module_OpenCvModule
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_droneproject_module_OpenCvModule_nativeStop
        (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_epfl_droneproject_module_OpenCvModule
 * Method:    nativeSetFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_droneproject_module_OpenCvModule_nativeSetFaceSize
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ch_epfl_droneproject_module_OpenCvModule
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_droneproject_module_OpenCvModule_nativeDetect
        (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
